## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
TOOLCHAIN := x86_64-linux-gcc
ALL_TARGETS += libs
ALL_TARGETS += examples
ALL_TARGETS += tools
ALL_TARGETS += docs

PREFIX=/usr/local
ifeq ($(MAKECMDGOALS),dist)
DIST_DIR?=vpx-vp8-vp9-nodocs-x86_64-linux-v1.15.2
else
DIST_DIR?=$(DESTDIR)/usr/local
endif
LIBSUBDIR=lib

VERSION_STRING=v1.15.2

VERSION_MAJOR=1
VERSION_MINOR=15
VERSION_PATCH=2

CONFIGURE_ARGS=
CONFIGURE_ARGS?=
